#define 加 +
#define 减 -
#define 乘 *
#define 除以 /
#define 取余 %
#define 的值为 =
#define 等于 ==
#define 输入 cin
#define 输入流 >>
#define 输出 cout
#define 输出流 <<
#define 语句结束 ;
#define 整数 int
#define 主函数 main
#define 循环 for
#define 使用 using
#define 命名空间 namespace
#define 标准 std
#define 返回 return
#define 换行 endl
#define 如果 if
#define 当 while
#define 真 true
#define 假 false
#define 大于 >
#define 大于等于 >=
#define 小于 <
#define 小于等于 <=
#define 结构体 struct
#define 加一 ++
#define 减一 --
#define 加等于 +=
#define 减等于 -=
#define 乘等于 *=
#define 除等于 /=
#define 余等于 %=
#define 长整数 long long
#define 短整数 short
#define 字符 char
#define 字符串 string
#define 操作 operator
#define 指针 *
#define 取值 *
#define 取址 &
#define 格式化输入 scanf
#define 格式化输出 printf
#define 格式 %
#define 包括 include
#define 定义宏 define
#define 否则如果 else if
#define 否则 else
#define 执行
#define 当条件成立继续执行 while
